// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: misc.proto

package jzs.msg.misc;

public final class Misc {
  private Misc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 jzcode = 1;
    /**
     * <code>required uint32 jzcode = 1;</code>
     */
    boolean hasJzcode();
    /**
     * <code>required uint32 jzcode = 1;</code>
     */
    int getJzcode();

    // required string symbol = 2;
    /**
     * <code>required string symbol = 2;</code>
     */
    boolean hasSymbol();
    /**
     * <code>required string symbol = 2;</code>
     */
    java.lang.String getSymbol();
    /**
     * <code>required string symbol = 2;</code>
     */
    com.google.protobuf.ByteString
        getSymbolBytes();
  }
  /**
   * Protobuf type {@code jzs.msg.misc.Code}
   *
   * <pre>
   * Qms Save tick
   * </pre>
   */
  public static final class Code extends
      com.google.protobuf.GeneratedMessage
      implements CodeOrBuilder {
    // Use Code.newBuilder() to construct.
    private Code(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Code(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Code defaultInstance;
    public static Code getDefaultInstance() {
      return defaultInstance;
    }

    public Code getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Code(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              jzcode_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              symbol_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_Code_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_Code_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jzs.msg.misc.Misc.Code.class, jzs.msg.misc.Misc.Code.Builder.class);
    }

    public static com.google.protobuf.Parser<Code> PARSER =
        new com.google.protobuf.AbstractParser<Code>() {
      public Code parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Code(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Code> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 jzcode = 1;
    public static final int JZCODE_FIELD_NUMBER = 1;
    private int jzcode_;
    /**
     * <code>required uint32 jzcode = 1;</code>
     */
    public boolean hasJzcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 jzcode = 1;</code>
     */
    public int getJzcode() {
      return jzcode_;
    }

    // required string symbol = 2;
    public static final int SYMBOL_FIELD_NUMBER = 2;
    private java.lang.Object symbol_;
    /**
     * <code>required string symbol = 2;</code>
     */
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string symbol = 2;</code>
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          symbol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string symbol = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      jzcode_ = 0;
      symbol_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasJzcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSymbol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, jzcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSymbolBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, jzcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSymbolBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jzs.msg.misc.Misc.Code parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.misc.Misc.Code parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.Code parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.misc.Misc.Code parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.Code parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.misc.Misc.Code parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.Code parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jzs.msg.misc.Misc.Code parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.Code parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.misc.Misc.Code parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jzs.msg.misc.Misc.Code prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jzs.msg.misc.Code}
     *
     * <pre>
     * Qms Save tick
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jzs.msg.misc.Misc.CodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_Code_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_Code_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jzs.msg.misc.Misc.Code.class, jzs.msg.misc.Misc.Code.Builder.class);
      }

      // Construct using jzs.msg.misc.Misc.Code.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        jzcode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        symbol_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_Code_descriptor;
      }

      public jzs.msg.misc.Misc.Code getDefaultInstanceForType() {
        return jzs.msg.misc.Misc.Code.getDefaultInstance();
      }

      public jzs.msg.misc.Misc.Code build() {
        jzs.msg.misc.Misc.Code result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jzs.msg.misc.Misc.Code buildPartial() {
        jzs.msg.misc.Misc.Code result = new jzs.msg.misc.Misc.Code(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jzcode_ = jzcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.symbol_ = symbol_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jzs.msg.misc.Misc.Code) {
          return mergeFrom((jzs.msg.misc.Misc.Code)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jzs.msg.misc.Misc.Code other) {
        if (other == jzs.msg.misc.Misc.Code.getDefaultInstance()) return this;
        if (other.hasJzcode()) {
          setJzcode(other.getJzcode());
        }
        if (other.hasSymbol()) {
          bitField0_ |= 0x00000002;
          symbol_ = other.symbol_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJzcode()) {
          
          return false;
        }
        if (!hasSymbol()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jzs.msg.misc.Misc.Code parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jzs.msg.misc.Misc.Code) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 jzcode = 1;
      private int jzcode_ ;
      /**
       * <code>required uint32 jzcode = 1;</code>
       */
      public boolean hasJzcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 jzcode = 1;</code>
       */
      public int getJzcode() {
        return jzcode_;
      }
      /**
       * <code>required uint32 jzcode = 1;</code>
       */
      public Builder setJzcode(int value) {
        bitField0_ |= 0x00000001;
        jzcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 jzcode = 1;</code>
       */
      public Builder clearJzcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jzcode_ = 0;
        onChanged();
        return this;
      }

      // required string symbol = 2;
      private java.lang.Object symbol_ = "";
      /**
       * <code>required string symbol = 2;</code>
       */
      public boolean hasSymbol() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string symbol = 2;</code>
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string symbol = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string symbol = 2;</code>
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string symbol = 2;</code>
       */
      public Builder clearSymbol() {
        bitField0_ = (bitField0_ & ~0x00000002);
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>required string symbol = 2;</code>
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        symbol_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jzs.msg.misc.Code)
    }

    static {
      defaultInstance = new Code(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jzs.msg.misc.Code)
  }

  public interface CodeTableOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 date = 1;
    /**
     * <code>required uint32 date = 1;</code>
     */
    boolean hasDate();
    /**
     * <code>required uint32 date = 1;</code>
     */
    int getDate();

    // repeated .jzs.msg.misc.Code codes = 2;
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    java.util.List<jzs.msg.misc.Misc.Code> 
        getCodesList();
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    jzs.msg.misc.Misc.Code getCodes(int index);
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    int getCodesCount();
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    java.util.List<? extends jzs.msg.misc.Misc.CodeOrBuilder> 
        getCodesOrBuilderList();
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    jzs.msg.misc.Misc.CodeOrBuilder getCodesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code jzs.msg.misc.CodeTable}
   */
  public static final class CodeTable extends
      com.google.protobuf.GeneratedMessage
      implements CodeTableOrBuilder {
    // Use CodeTable.newBuilder() to construct.
    private CodeTable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CodeTable(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CodeTable defaultInstance;
    public static CodeTable getDefaultInstance() {
      return defaultInstance;
    }

    public CodeTable getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CodeTable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              date_ = input.readUInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                codes_ = new java.util.ArrayList<jzs.msg.misc.Misc.Code>();
                mutable_bitField0_ |= 0x00000002;
              }
              codes_.add(input.readMessage(jzs.msg.misc.Misc.Code.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          codes_ = java.util.Collections.unmodifiableList(codes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_CodeTable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_CodeTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jzs.msg.misc.Misc.CodeTable.class, jzs.msg.misc.Misc.CodeTable.Builder.class);
    }

    public static com.google.protobuf.Parser<CodeTable> PARSER =
        new com.google.protobuf.AbstractParser<CodeTable>() {
      public CodeTable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CodeTable(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CodeTable> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 date = 1;
    public static final int DATE_FIELD_NUMBER = 1;
    private int date_;
    /**
     * <code>required uint32 date = 1;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 date = 1;</code>
     */
    public int getDate() {
      return date_;
    }

    // repeated .jzs.msg.misc.Code codes = 2;
    public static final int CODES_FIELD_NUMBER = 2;
    private java.util.List<jzs.msg.misc.Misc.Code> codes_;
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    public java.util.List<jzs.msg.misc.Misc.Code> getCodesList() {
      return codes_;
    }
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    public java.util.List<? extends jzs.msg.misc.Misc.CodeOrBuilder> 
        getCodesOrBuilderList() {
      return codes_;
    }
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    public int getCodesCount() {
      return codes_.size();
    }
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    public jzs.msg.misc.Misc.Code getCodes(int index) {
      return codes_.get(index);
    }
    /**
     * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
     */
    public jzs.msg.misc.Misc.CodeOrBuilder getCodesOrBuilder(
        int index) {
      return codes_.get(index);
    }

    private void initFields() {
      date_ = 0;
      codes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCodesCount(); i++) {
        if (!getCodes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, date_);
      }
      for (int i = 0; i < codes_.size(); i++) {
        output.writeMessage(2, codes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, date_);
      }
      for (int i = 0; i < codes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, codes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jzs.msg.misc.Misc.CodeTable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.misc.Misc.CodeTable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.CodeTable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.misc.Misc.CodeTable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.CodeTable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.misc.Misc.CodeTable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.CodeTable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jzs.msg.misc.Misc.CodeTable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.CodeTable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.misc.Misc.CodeTable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jzs.msg.misc.Misc.CodeTable prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jzs.msg.misc.CodeTable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jzs.msg.misc.Misc.CodeTableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_CodeTable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_CodeTable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jzs.msg.misc.Misc.CodeTable.class, jzs.msg.misc.Misc.CodeTable.Builder.class);
      }

      // Construct using jzs.msg.misc.Misc.CodeTable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCodesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        date_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (codesBuilder_ == null) {
          codes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          codesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_CodeTable_descriptor;
      }

      public jzs.msg.misc.Misc.CodeTable getDefaultInstanceForType() {
        return jzs.msg.misc.Misc.CodeTable.getDefaultInstance();
      }

      public jzs.msg.misc.Misc.CodeTable build() {
        jzs.msg.misc.Misc.CodeTable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jzs.msg.misc.Misc.CodeTable buildPartial() {
        jzs.msg.misc.Misc.CodeTable result = new jzs.msg.misc.Misc.CodeTable(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (codesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            codes_ = java.util.Collections.unmodifiableList(codes_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.codes_ = codes_;
        } else {
          result.codes_ = codesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jzs.msg.misc.Misc.CodeTable) {
          return mergeFrom((jzs.msg.misc.Misc.CodeTable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jzs.msg.misc.Misc.CodeTable other) {
        if (other == jzs.msg.misc.Misc.CodeTable.getDefaultInstance()) return this;
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (codesBuilder_ == null) {
          if (!other.codes_.isEmpty()) {
            if (codes_.isEmpty()) {
              codes_ = other.codes_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCodesIsMutable();
              codes_.addAll(other.codes_);
            }
            onChanged();
          }
        } else {
          if (!other.codes_.isEmpty()) {
            if (codesBuilder_.isEmpty()) {
              codesBuilder_.dispose();
              codesBuilder_ = null;
              codes_ = other.codes_;
              bitField0_ = (bitField0_ & ~0x00000002);
              codesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCodesFieldBuilder() : null;
            } else {
              codesBuilder_.addAllMessages(other.codes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        for (int i = 0; i < getCodesCount(); i++) {
          if (!getCodes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jzs.msg.misc.Misc.CodeTable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jzs.msg.misc.Misc.CodeTable) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 date = 1;
      private int date_ ;
      /**
       * <code>required uint32 date = 1;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 date = 1;</code>
       */
      public int getDate() {
        return date_;
      }
      /**
       * <code>required uint32 date = 1;</code>
       */
      public Builder setDate(int value) {
        bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 date = 1;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = 0;
        onChanged();
        return this;
      }

      // repeated .jzs.msg.misc.Code codes = 2;
      private java.util.List<jzs.msg.misc.Misc.Code> codes_ =
        java.util.Collections.emptyList();
      private void ensureCodesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          codes_ = new java.util.ArrayList<jzs.msg.misc.Misc.Code>(codes_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          jzs.msg.misc.Misc.Code, jzs.msg.misc.Misc.Code.Builder, jzs.msg.misc.Misc.CodeOrBuilder> codesBuilder_;

      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public java.util.List<jzs.msg.misc.Misc.Code> getCodesList() {
        if (codesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(codes_);
        } else {
          return codesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public int getCodesCount() {
        if (codesBuilder_ == null) {
          return codes_.size();
        } else {
          return codesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public jzs.msg.misc.Misc.Code getCodes(int index) {
        if (codesBuilder_ == null) {
          return codes_.get(index);
        } else {
          return codesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public Builder setCodes(
          int index, jzs.msg.misc.Misc.Code value) {
        if (codesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCodesIsMutable();
          codes_.set(index, value);
          onChanged();
        } else {
          codesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public Builder setCodes(
          int index, jzs.msg.misc.Misc.Code.Builder builderForValue) {
        if (codesBuilder_ == null) {
          ensureCodesIsMutable();
          codes_.set(index, builderForValue.build());
          onChanged();
        } else {
          codesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public Builder addCodes(jzs.msg.misc.Misc.Code value) {
        if (codesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCodesIsMutable();
          codes_.add(value);
          onChanged();
        } else {
          codesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public Builder addCodes(
          int index, jzs.msg.misc.Misc.Code value) {
        if (codesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCodesIsMutable();
          codes_.add(index, value);
          onChanged();
        } else {
          codesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public Builder addCodes(
          jzs.msg.misc.Misc.Code.Builder builderForValue) {
        if (codesBuilder_ == null) {
          ensureCodesIsMutable();
          codes_.add(builderForValue.build());
          onChanged();
        } else {
          codesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public Builder addCodes(
          int index, jzs.msg.misc.Misc.Code.Builder builderForValue) {
        if (codesBuilder_ == null) {
          ensureCodesIsMutable();
          codes_.add(index, builderForValue.build());
          onChanged();
        } else {
          codesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public Builder addAllCodes(
          java.lang.Iterable<? extends jzs.msg.misc.Misc.Code> values) {
        if (codesBuilder_ == null) {
          ensureCodesIsMutable();
          super.addAll(values, codes_);
          onChanged();
        } else {
          codesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public Builder clearCodes() {
        if (codesBuilder_ == null) {
          codes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          codesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public Builder removeCodes(int index) {
        if (codesBuilder_ == null) {
          ensureCodesIsMutable();
          codes_.remove(index);
          onChanged();
        } else {
          codesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public jzs.msg.misc.Misc.Code.Builder getCodesBuilder(
          int index) {
        return getCodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public jzs.msg.misc.Misc.CodeOrBuilder getCodesOrBuilder(
          int index) {
        if (codesBuilder_ == null) {
          return codes_.get(index);  } else {
          return codesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public java.util.List<? extends jzs.msg.misc.Misc.CodeOrBuilder> 
           getCodesOrBuilderList() {
        if (codesBuilder_ != null) {
          return codesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(codes_);
        }
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public jzs.msg.misc.Misc.Code.Builder addCodesBuilder() {
        return getCodesFieldBuilder().addBuilder(
            jzs.msg.misc.Misc.Code.getDefaultInstance());
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public jzs.msg.misc.Misc.Code.Builder addCodesBuilder(
          int index) {
        return getCodesFieldBuilder().addBuilder(
            index, jzs.msg.misc.Misc.Code.getDefaultInstance());
      }
      /**
       * <code>repeated .jzs.msg.misc.Code codes = 2;</code>
       */
      public java.util.List<jzs.msg.misc.Misc.Code.Builder> 
           getCodesBuilderList() {
        return getCodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          jzs.msg.misc.Misc.Code, jzs.msg.misc.Misc.Code.Builder, jzs.msg.misc.Misc.CodeOrBuilder> 
          getCodesFieldBuilder() {
        if (codesBuilder_ == null) {
          codesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              jzs.msg.misc.Misc.Code, jzs.msg.misc.Misc.Code.Builder, jzs.msg.misc.Misc.CodeOrBuilder>(
                  codes_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          codes_ = null;
        }
        return codesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:jzs.msg.misc.CodeTable)
    }

    static {
      defaultInstance = new CodeTable(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jzs.msg.misc.CodeTable)
  }

  public interface LowHeartBeatReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 req_id = 1;
    /**
     * <code>required uint32 req_id = 1;</code>
     */
    boolean hasReqId();
    /**
     * <code>required uint32 req_id = 1;</code>
     */
    int getReqId();

    // required uint64 req_time = 2;
    /**
     * <code>required uint64 req_time = 2;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    boolean hasReqTime();
    /**
     * <code>required uint64 req_time = 2;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    long getReqTime();
  }
  /**
   * Protobuf type {@code jzs.msg.misc.LowHeartBeatReq}
   */
  public static final class LowHeartBeatReq extends
      com.google.protobuf.GeneratedMessage
      implements LowHeartBeatReqOrBuilder {
    // Use LowHeartBeatReq.newBuilder() to construct.
    private LowHeartBeatReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LowHeartBeatReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LowHeartBeatReq defaultInstance;
    public static LowHeartBeatReq getDefaultInstance() {
      return defaultInstance;
    }

    public LowHeartBeatReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LowHeartBeatReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reqId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              reqTime_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jzs.msg.misc.Misc.LowHeartBeatReq.class, jzs.msg.misc.Misc.LowHeartBeatReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LowHeartBeatReq> PARSER =
        new com.google.protobuf.AbstractParser<LowHeartBeatReq>() {
      public LowHeartBeatReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LowHeartBeatReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LowHeartBeatReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 req_id = 1;
    public static final int REQ_ID_FIELD_NUMBER = 1;
    private int reqId_;
    /**
     * <code>required uint32 req_id = 1;</code>
     */
    public boolean hasReqId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 req_id = 1;</code>
     */
    public int getReqId() {
      return reqId_;
    }

    // required uint64 req_time = 2;
    public static final int REQ_TIME_FIELD_NUMBER = 2;
    private long reqTime_;
    /**
     * <code>required uint64 req_time = 2;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    public boolean hasReqTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 req_time = 2;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    public long getReqTime() {
      return reqTime_;
    }

    private void initFields() {
      reqId_ = 0;
      reqTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, reqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, reqTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, reqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, reqTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jzs.msg.misc.Misc.LowHeartBeatReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jzs.msg.misc.Misc.LowHeartBeatReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jzs.msg.misc.LowHeartBeatReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jzs.msg.misc.Misc.LowHeartBeatReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jzs.msg.misc.Misc.LowHeartBeatReq.class, jzs.msg.misc.Misc.LowHeartBeatReq.Builder.class);
      }

      // Construct using jzs.msg.misc.Misc.LowHeartBeatReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        reqTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatReq_descriptor;
      }

      public jzs.msg.misc.Misc.LowHeartBeatReq getDefaultInstanceForType() {
        return jzs.msg.misc.Misc.LowHeartBeatReq.getDefaultInstance();
      }

      public jzs.msg.misc.Misc.LowHeartBeatReq build() {
        jzs.msg.misc.Misc.LowHeartBeatReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jzs.msg.misc.Misc.LowHeartBeatReq buildPartial() {
        jzs.msg.misc.Misc.LowHeartBeatReq result = new jzs.msg.misc.Misc.LowHeartBeatReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqId_ = reqId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqTime_ = reqTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jzs.msg.misc.Misc.LowHeartBeatReq) {
          return mergeFrom((jzs.msg.misc.Misc.LowHeartBeatReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jzs.msg.misc.Misc.LowHeartBeatReq other) {
        if (other == jzs.msg.misc.Misc.LowHeartBeatReq.getDefaultInstance()) return this;
        if (other.hasReqId()) {
          setReqId(other.getReqId());
        }
        if (other.hasReqTime()) {
          setReqTime(other.getReqTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqId()) {
          
          return false;
        }
        if (!hasReqTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jzs.msg.misc.Misc.LowHeartBeatReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jzs.msg.misc.Misc.LowHeartBeatReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 req_id = 1;
      private int reqId_ ;
      /**
       * <code>required uint32 req_id = 1;</code>
       */
      public boolean hasReqId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 req_id = 1;</code>
       */
      public int getReqId() {
        return reqId_;
      }
      /**
       * <code>required uint32 req_id = 1;</code>
       */
      public Builder setReqId(int value) {
        bitField0_ |= 0x00000001;
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 req_id = 1;</code>
       */
      public Builder clearReqId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqId_ = 0;
        onChanged();
        return this;
      }

      // required uint64 req_time = 2;
      private long reqTime_ ;
      /**
       * <code>required uint64 req_time = 2;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public boolean hasReqTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 req_time = 2;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public long getReqTime() {
        return reqTime_;
      }
      /**
       * <code>required uint64 req_time = 2;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public Builder setReqTime(long value) {
        bitField0_ |= 0x00000002;
        reqTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 req_time = 2;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public Builder clearReqTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jzs.msg.misc.LowHeartBeatReq)
    }

    static {
      defaultInstance = new LowHeartBeatReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jzs.msg.misc.LowHeartBeatReq)
  }

  public interface LowHeartBeatRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 req_id = 1;
    /**
     * <code>required uint32 req_id = 1;</code>
     */
    boolean hasReqId();
    /**
     * <code>required uint32 req_id = 1;</code>
     */
    int getReqId();

    // required uint64 req_time = 2;
    /**
     * <code>required uint64 req_time = 2;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    boolean hasReqTime();
    /**
     * <code>required uint64 req_time = 2;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    long getReqTime();

    // required uint64 rsp_time = 3;
    /**
     * <code>required uint64 rsp_time = 3;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    boolean hasRspTime();
    /**
     * <code>required uint64 rsp_time = 3;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    long getRspTime();
  }
  /**
   * Protobuf type {@code jzs.msg.misc.LowHeartBeatRsp}
   */
  public static final class LowHeartBeatRsp extends
      com.google.protobuf.GeneratedMessage
      implements LowHeartBeatRspOrBuilder {
    // Use LowHeartBeatRsp.newBuilder() to construct.
    private LowHeartBeatRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LowHeartBeatRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LowHeartBeatRsp defaultInstance;
    public static LowHeartBeatRsp getDefaultInstance() {
      return defaultInstance;
    }

    public LowHeartBeatRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LowHeartBeatRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reqId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              reqTime_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rspTime_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jzs.msg.misc.Misc.LowHeartBeatRsp.class, jzs.msg.misc.Misc.LowHeartBeatRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<LowHeartBeatRsp> PARSER =
        new com.google.protobuf.AbstractParser<LowHeartBeatRsp>() {
      public LowHeartBeatRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LowHeartBeatRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LowHeartBeatRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 req_id = 1;
    public static final int REQ_ID_FIELD_NUMBER = 1;
    private int reqId_;
    /**
     * <code>required uint32 req_id = 1;</code>
     */
    public boolean hasReqId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 req_id = 1;</code>
     */
    public int getReqId() {
      return reqId_;
    }

    // required uint64 req_time = 2;
    public static final int REQ_TIME_FIELD_NUMBER = 2;
    private long reqTime_;
    /**
     * <code>required uint64 req_time = 2;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    public boolean hasReqTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 req_time = 2;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    public long getReqTime() {
      return reqTime_;
    }

    // required uint64 rsp_time = 3;
    public static final int RSP_TIME_FIELD_NUMBER = 3;
    private long rspTime_;
    /**
     * <code>required uint64 rsp_time = 3;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    public boolean hasRspTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 rsp_time = 3;</code>
     *
     * <pre>
     * ms
     * </pre>
     */
    public long getRspTime() {
      return rspTime_;
    }

    private void initFields() {
      reqId_ = 0;
      reqTime_ = 0L;
      rspTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRspTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, reqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, reqTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, rspTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, reqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, reqTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, rspTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.misc.Misc.LowHeartBeatRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jzs.msg.misc.Misc.LowHeartBeatRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jzs.msg.misc.LowHeartBeatRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jzs.msg.misc.Misc.LowHeartBeatRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jzs.msg.misc.Misc.LowHeartBeatRsp.class, jzs.msg.misc.Misc.LowHeartBeatRsp.Builder.class);
      }

      // Construct using jzs.msg.misc.Misc.LowHeartBeatRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        reqTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        rspTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jzs.msg.misc.Misc.internal_static_jzs_msg_misc_LowHeartBeatRsp_descriptor;
      }

      public jzs.msg.misc.Misc.LowHeartBeatRsp getDefaultInstanceForType() {
        return jzs.msg.misc.Misc.LowHeartBeatRsp.getDefaultInstance();
      }

      public jzs.msg.misc.Misc.LowHeartBeatRsp build() {
        jzs.msg.misc.Misc.LowHeartBeatRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jzs.msg.misc.Misc.LowHeartBeatRsp buildPartial() {
        jzs.msg.misc.Misc.LowHeartBeatRsp result = new jzs.msg.misc.Misc.LowHeartBeatRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqId_ = reqId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqTime_ = reqTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rspTime_ = rspTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jzs.msg.misc.Misc.LowHeartBeatRsp) {
          return mergeFrom((jzs.msg.misc.Misc.LowHeartBeatRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jzs.msg.misc.Misc.LowHeartBeatRsp other) {
        if (other == jzs.msg.misc.Misc.LowHeartBeatRsp.getDefaultInstance()) return this;
        if (other.hasReqId()) {
          setReqId(other.getReqId());
        }
        if (other.hasReqTime()) {
          setReqTime(other.getReqTime());
        }
        if (other.hasRspTime()) {
          setRspTime(other.getRspTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqId()) {
          
          return false;
        }
        if (!hasReqTime()) {
          
          return false;
        }
        if (!hasRspTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jzs.msg.misc.Misc.LowHeartBeatRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jzs.msg.misc.Misc.LowHeartBeatRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 req_id = 1;
      private int reqId_ ;
      /**
       * <code>required uint32 req_id = 1;</code>
       */
      public boolean hasReqId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 req_id = 1;</code>
       */
      public int getReqId() {
        return reqId_;
      }
      /**
       * <code>required uint32 req_id = 1;</code>
       */
      public Builder setReqId(int value) {
        bitField0_ |= 0x00000001;
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 req_id = 1;</code>
       */
      public Builder clearReqId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqId_ = 0;
        onChanged();
        return this;
      }

      // required uint64 req_time = 2;
      private long reqTime_ ;
      /**
       * <code>required uint64 req_time = 2;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public boolean hasReqTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 req_time = 2;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public long getReqTime() {
        return reqTime_;
      }
      /**
       * <code>required uint64 req_time = 2;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public Builder setReqTime(long value) {
        bitField0_ |= 0x00000002;
        reqTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 req_time = 2;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public Builder clearReqTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqTime_ = 0L;
        onChanged();
        return this;
      }

      // required uint64 rsp_time = 3;
      private long rspTime_ ;
      /**
       * <code>required uint64 rsp_time = 3;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public boolean hasRspTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 rsp_time = 3;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public long getRspTime() {
        return rspTime_;
      }
      /**
       * <code>required uint64 rsp_time = 3;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public Builder setRspTime(long value) {
        bitField0_ |= 0x00000004;
        rspTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 rsp_time = 3;</code>
       *
       * <pre>
       * ms
       * </pre>
       */
      public Builder clearRspTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rspTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jzs.msg.misc.LowHeartBeatRsp)
    }

    static {
      defaultInstance = new LowHeartBeatRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jzs.msg.misc.LowHeartBeatRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jzs_msg_misc_Code_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jzs_msg_misc_Code_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jzs_msg_misc_CodeTable_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jzs_msg_misc_CodeTable_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jzs_msg_misc_LowHeartBeatReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jzs_msg_misc_LowHeartBeatReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jzs_msg_misc_LowHeartBeatRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jzs_msg_misc_LowHeartBeatRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmisc.proto\022\014jzs.msg.misc\"&\n\004Code\022\016\n\006jz" +
      "code\030\001 \002(\r\022\016\n\006symbol\030\002 \002(\t\"<\n\tCodeTable\022" +
      "\014\n\004date\030\001 \002(\r\022!\n\005codes\030\002 \003(\0132\022.jzs.msg.m" +
      "isc.Code\"3\n\017LowHeartBeatReq\022\016\n\006req_id\030\001 " +
      "\002(\r\022\020\n\010req_time\030\002 \002(\004\"E\n\017LowHeartBeatRsp" +
      "\022\016\n\006req_id\030\001 \002(\r\022\020\n\010req_time\030\002 \002(\004\022\020\n\010rs" +
      "p_time\030\003 \002(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_jzs_msg_misc_Code_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_jzs_msg_misc_Code_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jzs_msg_misc_Code_descriptor,
              new java.lang.String[] { "Jzcode", "Symbol", });
          internal_static_jzs_msg_misc_CodeTable_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_jzs_msg_misc_CodeTable_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jzs_msg_misc_CodeTable_descriptor,
              new java.lang.String[] { "Date", "Codes", });
          internal_static_jzs_msg_misc_LowHeartBeatReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_jzs_msg_misc_LowHeartBeatReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jzs_msg_misc_LowHeartBeatReq_descriptor,
              new java.lang.String[] { "ReqId", "ReqTime", });
          internal_static_jzs_msg_misc_LowHeartBeatRsp_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_jzs_msg_misc_LowHeartBeatRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jzs_msg_misc_LowHeartBeatRsp_descriptor,
              new java.lang.String[] { "ReqId", "ReqTime", "RspTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
