// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jzs.proto

package jzs.msg;

public final class Jzs {
  private Jzs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code jzs.msg.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG_SYS_INIT = 0;</code>
     */
    MSG_SYS_INIT(0, 0),
    /**
     * <code>MSG_SYS_TIMER = 1;</code>
     */
    MSG_SYS_TIMER(1, 1),
    /**
     * <code>MSG_LOW_HEARTBEAT_REQ = 2;</code>
     */
    MSG_LOW_HEARTBEAT_REQ(2, 2),
    /**
     * <code>MSG_LOW_HEARTBEAT_RSP = 3;</code>
     */
    MSG_LOW_HEARTBEAT_RSP(3, 3),
    /**
     * <code>MSG_TD_ORDER_REQ = 10;</code>
     *
     * <pre>
     * TDLINK interface
     * </pre>
     */
    MSG_TD_ORDER_REQ(4, 10),
    /**
     * <code>MSG_TD_ORDER_RSP = 11;</code>
     */
    MSG_TD_ORDER_RSP(5, 11),
    /**
     * <code>MSG_TD_ORDER_REPORT_IND = 12;</code>
     */
    MSG_TD_ORDER_REPORT_IND(6, 12),
    /**
     * <code>MSG_TD_QUERY_ACCOUNT_REQ = 13;</code>
     */
    MSG_TD_QUERY_ACCOUNT_REQ(7, 13),
    /**
     * <code>MSG_TD_QUERY_ACCOUNT_RSP = 14;</code>
     */
    MSG_TD_QUERY_ACCOUNT_RSP(8, 14),
    /**
     * <code>MSG_TD_QUERY_POSITION_REQ = 15;</code>
     */
    MSG_TD_QUERY_POSITION_REQ(9, 15),
    /**
     * <code>MSG_TD_QUERY_POSITION_RSP = 16;</code>
     */
    MSG_TD_QUERY_POSITION_RSP(10, 16),
    /**
     * <code>MSG_TD_CANCEL_ORDER_REQ = 17;</code>
     */
    MSG_TD_CANCEL_ORDER_REQ(11, 17),
    /**
     * <code>MSG_TD_CANCEL_ORDER_RSP = 18;</code>
     */
    MSG_TD_CANCEL_ORDER_RSP(12, 18),
    /**
     * <code>MSG_TD_QUERY_TRADE_REQ = 80;</code>
     */
    MSG_TD_QUERY_TRADE_REQ(13, 80),
    /**
     * <code>MSG_TD_QUERY_TRADE_RSP = 81;</code>
     */
    MSG_TD_QUERY_TRADE_RSP(14, 81),
    /**
     * <code>MSG_QMS_MARKETQUOTE_REQ = 20;</code>
     *
     * <pre>
     * QMS    
     * </pre>
     */
    MSG_QMS_MARKETQUOTE_REQ(15, 20),
    /**
     * <code>MSG_QMS_MARKETQUOTE_RSP = 21;</code>
     */
    MSG_QMS_MARKETQUOTE_RSP(16, 21),
    /**
     * <code>MSG_QMS_BAR_1M_REQ = 22;</code>
     */
    MSG_QMS_BAR_1M_REQ(17, 22),
    /**
     * <code>MSG_QMS_BAR_1M_RSP = 23;</code>
     */
    MSG_QMS_BAR_1M_RSP(18, 23),
    /**
     * <code>MSG_QMS_STRATEGY_MARKETQUOTES_REQ = 24;</code>
     */
    MSG_QMS_STRATEGY_MARKETQUOTES_REQ(19, 24),
    /**
     * <code>MSG_QMS_STRATEGY_MARKETQUOTES_RSP = 25;</code>
     */
    MSG_QMS_STRATEGY_MARKETQUOTES_RSP(20, 25),
    /**
     * <code>MSG_QMS_STRATEGY_SUBSCRIBE_REQ = 26;</code>
     */
    MSG_QMS_STRATEGY_SUBSCRIBE_REQ(21, 26),
    /**
     * <code>MSG_QMS_STRATEGY_SUBSCRIBE_RSP = 27;</code>
     */
    MSG_QMS_STRATEGY_SUBSCRIBE_RSP(22, 27),
    /**
     * <code>MSG_MD_MARKETDATA_IND = 31;</code>
     *
     * <pre>
     * MD interface
     * </pre>
     */
    MSG_MD_MARKETDATA_IND(23, 31),
    /**
     * <code>MSG_OMS_GOAL_PORTFOLIO_REQ = 40;</code>
     *
     * <pre>
     * OMS interface
     * </pre>
     */
    MSG_OMS_GOAL_PORTFOLIO_REQ(24, 40),
    /**
     * <code>MSG_OMS_GOAL_PORTFOLIO_RSP = 41;</code>
     */
    MSG_OMS_GOAL_PORTFOLIO_RSP(25, 41),
    /**
     * <code>MSG_OMS_QUERY_PORTFOLIO_REQ = 42;</code>
     */
    MSG_OMS_QUERY_PORTFOLIO_REQ(26, 42),
    /**
     * <code>MSG_OMS_QUERY_PORTFOLIO_RSP = 43;</code>
     */
    MSG_OMS_QUERY_PORTFOLIO_RSP(27, 43),
    /**
     * <code>MSG_OMS_SET_PANIC_REQ = 44;</code>
     */
    MSG_OMS_SET_PANIC_REQ(28, 44),
    /**
     * <code>MSG_OMS_SET_PANIC_RSP = 45;</code>
     */
    MSG_OMS_SET_PANIC_RSP(29, 45),
    /**
     * <code>MSG_OMS_SYNC_ACCOUNT_REQ = 46;</code>
     */
    MSG_OMS_SYNC_ACCOUNT_REQ(30, 46),
    /**
     * <code>MSG_OMS_SYNC_ACCOUNT_RSP = 47;</code>
     */
    MSG_OMS_SYNC_ACCOUNT_RSP(31, 47),
    /**
     * <code>MSG_OMS_QUERY_ACCOUNT_REQ = 48;</code>
     */
    MSG_OMS_QUERY_ACCOUNT_REQ(32, 48),
    /**
     * <code>MSG_OMS_QUERY_ACCOUNT_RSP = 49;</code>
     */
    MSG_OMS_QUERY_ACCOUNT_RSP(33, 49),
    /**
     * <code>MSG_OMS_BASKET_ORDER_REQ = 70;</code>
     */
    MSG_OMS_BASKET_ORDER_REQ(34, 70),
    /**
     * <code>MSG_OMS_BASKET_ORDER_RSP = 71;</code>
     */
    MSG_OMS_BASKET_ORDER_RSP(35, 71),
    /**
     * <code>MSG_OMS_STOP_PORTFOLIO_REQ = 72;</code>
     */
    MSG_OMS_STOP_PORTFOLIO_REQ(36, 72),
    /**
     * <code>MSG_OMS_STOP_PORTFOLIO_RSP = 73;</code>
     */
    MSG_OMS_STOP_PORTFOLIO_RSP(37, 73),
    /**
     * <code>MSG_EMS_ORDER_REQ = 50;</code>
     *
     * <pre>
     * EMS Interface
     * </pre>
     */
    MSG_EMS_ORDER_REQ(38, 50),
    /**
     * <code>MSG_EMS_ORDER_RSP = 51;</code>
     */
    MSG_EMS_ORDER_RSP(39, 51),
    /**
     * <code>MSG_EMS_ORDER_REPORT_IND = 52;</code>
     */
    MSG_EMS_ORDER_REPORT_IND(40, 52),
    /**
     * <code>MSG_EMS_CANCEL_ORDER_REQ = 53;</code>
     */
    MSG_EMS_CANCEL_ORDER_REQ(41, 53),
    /**
     * <code>MSG_EMS_CANCEL_ORDER_RSP = 54;</code>
     */
    MSG_EMS_CANCEL_ORDER_RSP(42, 54),
    /**
     * <code>MSG_MISC_GET_TDTICKET_REQ = 60;</code>
     *
     * <pre>
     * MISC Interface
     * </pre>
     */
    MSG_MISC_GET_TDTICKET_REQ(43, 60),
    /**
     * <code>MSG_MISC_GET_TDTICKET_RSP = 61;</code>
     */
    MSG_MISC_GET_TDTICKET_RSP(44, 61),
    /**
     * <code>MSG_MISC_SELF_MESSAGE = 62;</code>
     */
    MSG_MISC_SELF_MESSAGE(45, 62),
    /**
     * <code>MSG_TRANS_TRANSACTION = 91;</code>
     *
     * <pre>
     * Transaction interface
     * </pre>
     */
    MSG_TRANS_TRANSACTION(46, 91),
    /**
     * <code>MSG_TRANS_GET_TRANSACTION_REQ = 92;</code>
     */
    MSG_TRANS_GET_TRANSACTION_REQ(47, 92),
    /**
     * <code>MSG_TRANS_GET_TRANSACTION_RSP = 93;</code>
     */
    MSG_TRANS_GET_TRANSACTION_RSP(48, 93),
    /**
     * <code>MSG_ORDER_ORDER = 94;</code>
     *
     * <pre>
     *Order interface
     * </pre>
     */
    MSG_ORDER_ORDER(49, 94),
    /**
     * <code>MSG_ORDER_GET_ORDER_REQ = 95;</code>
     */
    MSG_ORDER_GET_ORDER_REQ(50, 95),
    /**
     * <code>MSG_ORDER_GET_ORDER_RSP = 96;</code>
     */
    MSG_ORDER_GET_ORDER_RSP(51, 96),
    ;

    /**
     * <code>MSG_SYS_INIT = 0;</code>
     */
    public static final int MSG_SYS_INIT_VALUE = 0;
    /**
     * <code>MSG_SYS_TIMER = 1;</code>
     */
    public static final int MSG_SYS_TIMER_VALUE = 1;
    /**
     * <code>MSG_LOW_HEARTBEAT_REQ = 2;</code>
     */
    public static final int MSG_LOW_HEARTBEAT_REQ_VALUE = 2;
    /**
     * <code>MSG_LOW_HEARTBEAT_RSP = 3;</code>
     */
    public static final int MSG_LOW_HEARTBEAT_RSP_VALUE = 3;
    /**
     * <code>MSG_TD_ORDER_REQ = 10;</code>
     *
     * <pre>
     * TDLINK interface
     * </pre>
     */
    public static final int MSG_TD_ORDER_REQ_VALUE = 10;
    /**
     * <code>MSG_TD_ORDER_RSP = 11;</code>
     */
    public static final int MSG_TD_ORDER_RSP_VALUE = 11;
    /**
     * <code>MSG_TD_ORDER_REPORT_IND = 12;</code>
     */
    public static final int MSG_TD_ORDER_REPORT_IND_VALUE = 12;
    /**
     * <code>MSG_TD_QUERY_ACCOUNT_REQ = 13;</code>
     */
    public static final int MSG_TD_QUERY_ACCOUNT_REQ_VALUE = 13;
    /**
     * <code>MSG_TD_QUERY_ACCOUNT_RSP = 14;</code>
     */
    public static final int MSG_TD_QUERY_ACCOUNT_RSP_VALUE = 14;
    /**
     * <code>MSG_TD_QUERY_POSITION_REQ = 15;</code>
     */
    public static final int MSG_TD_QUERY_POSITION_REQ_VALUE = 15;
    /**
     * <code>MSG_TD_QUERY_POSITION_RSP = 16;</code>
     */
    public static final int MSG_TD_QUERY_POSITION_RSP_VALUE = 16;
    /**
     * <code>MSG_TD_CANCEL_ORDER_REQ = 17;</code>
     */
    public static final int MSG_TD_CANCEL_ORDER_REQ_VALUE = 17;
    /**
     * <code>MSG_TD_CANCEL_ORDER_RSP = 18;</code>
     */
    public static final int MSG_TD_CANCEL_ORDER_RSP_VALUE = 18;
    /**
     * <code>MSG_TD_QUERY_TRADE_REQ = 80;</code>
     */
    public static final int MSG_TD_QUERY_TRADE_REQ_VALUE = 80;
    /**
     * <code>MSG_TD_QUERY_TRADE_RSP = 81;</code>
     */
    public static final int MSG_TD_QUERY_TRADE_RSP_VALUE = 81;
    /**
     * <code>MSG_QMS_MARKETQUOTE_REQ = 20;</code>
     *
     * <pre>
     * QMS    
     * </pre>
     */
    public static final int MSG_QMS_MARKETQUOTE_REQ_VALUE = 20;
    /**
     * <code>MSG_QMS_MARKETQUOTE_RSP = 21;</code>
     */
    public static final int MSG_QMS_MARKETQUOTE_RSP_VALUE = 21;
    /**
     * <code>MSG_QMS_BAR_1M_REQ = 22;</code>
     */
    public static final int MSG_QMS_BAR_1M_REQ_VALUE = 22;
    /**
     * <code>MSG_QMS_BAR_1M_RSP = 23;</code>
     */
    public static final int MSG_QMS_BAR_1M_RSP_VALUE = 23;
    /**
     * <code>MSG_QMS_STRATEGY_MARKETQUOTES_REQ = 24;</code>
     */
    public static final int MSG_QMS_STRATEGY_MARKETQUOTES_REQ_VALUE = 24;
    /**
     * <code>MSG_QMS_STRATEGY_MARKETQUOTES_RSP = 25;</code>
     */
    public static final int MSG_QMS_STRATEGY_MARKETQUOTES_RSP_VALUE = 25;
    /**
     * <code>MSG_QMS_STRATEGY_SUBSCRIBE_REQ = 26;</code>
     */
    public static final int MSG_QMS_STRATEGY_SUBSCRIBE_REQ_VALUE = 26;
    /**
     * <code>MSG_QMS_STRATEGY_SUBSCRIBE_RSP = 27;</code>
     */
    public static final int MSG_QMS_STRATEGY_SUBSCRIBE_RSP_VALUE = 27;
    /**
     * <code>MSG_MD_MARKETDATA_IND = 31;</code>
     *
     * <pre>
     * MD interface
     * </pre>
     */
    public static final int MSG_MD_MARKETDATA_IND_VALUE = 31;
    /**
     * <code>MSG_OMS_GOAL_PORTFOLIO_REQ = 40;</code>
     *
     * <pre>
     * OMS interface
     * </pre>
     */
    public static final int MSG_OMS_GOAL_PORTFOLIO_REQ_VALUE = 40;
    /**
     * <code>MSG_OMS_GOAL_PORTFOLIO_RSP = 41;</code>
     */
    public static final int MSG_OMS_GOAL_PORTFOLIO_RSP_VALUE = 41;
    /**
     * <code>MSG_OMS_QUERY_PORTFOLIO_REQ = 42;</code>
     */
    public static final int MSG_OMS_QUERY_PORTFOLIO_REQ_VALUE = 42;
    /**
     * <code>MSG_OMS_QUERY_PORTFOLIO_RSP = 43;</code>
     */
    public static final int MSG_OMS_QUERY_PORTFOLIO_RSP_VALUE = 43;
    /**
     * <code>MSG_OMS_SET_PANIC_REQ = 44;</code>
     */
    public static final int MSG_OMS_SET_PANIC_REQ_VALUE = 44;
    /**
     * <code>MSG_OMS_SET_PANIC_RSP = 45;</code>
     */
    public static final int MSG_OMS_SET_PANIC_RSP_VALUE = 45;
    /**
     * <code>MSG_OMS_SYNC_ACCOUNT_REQ = 46;</code>
     */
    public static final int MSG_OMS_SYNC_ACCOUNT_REQ_VALUE = 46;
    /**
     * <code>MSG_OMS_SYNC_ACCOUNT_RSP = 47;</code>
     */
    public static final int MSG_OMS_SYNC_ACCOUNT_RSP_VALUE = 47;
    /**
     * <code>MSG_OMS_QUERY_ACCOUNT_REQ = 48;</code>
     */
    public static final int MSG_OMS_QUERY_ACCOUNT_REQ_VALUE = 48;
    /**
     * <code>MSG_OMS_QUERY_ACCOUNT_RSP = 49;</code>
     */
    public static final int MSG_OMS_QUERY_ACCOUNT_RSP_VALUE = 49;
    /**
     * <code>MSG_OMS_BASKET_ORDER_REQ = 70;</code>
     */
    public static final int MSG_OMS_BASKET_ORDER_REQ_VALUE = 70;
    /**
     * <code>MSG_OMS_BASKET_ORDER_RSP = 71;</code>
     */
    public static final int MSG_OMS_BASKET_ORDER_RSP_VALUE = 71;
    /**
     * <code>MSG_OMS_STOP_PORTFOLIO_REQ = 72;</code>
     */
    public static final int MSG_OMS_STOP_PORTFOLIO_REQ_VALUE = 72;
    /**
     * <code>MSG_OMS_STOP_PORTFOLIO_RSP = 73;</code>
     */
    public static final int MSG_OMS_STOP_PORTFOLIO_RSP_VALUE = 73;
    /**
     * <code>MSG_EMS_ORDER_REQ = 50;</code>
     *
     * <pre>
     * EMS Interface
     * </pre>
     */
    public static final int MSG_EMS_ORDER_REQ_VALUE = 50;
    /**
     * <code>MSG_EMS_ORDER_RSP = 51;</code>
     */
    public static final int MSG_EMS_ORDER_RSP_VALUE = 51;
    /**
     * <code>MSG_EMS_ORDER_REPORT_IND = 52;</code>
     */
    public static final int MSG_EMS_ORDER_REPORT_IND_VALUE = 52;
    /**
     * <code>MSG_EMS_CANCEL_ORDER_REQ = 53;</code>
     */
    public static final int MSG_EMS_CANCEL_ORDER_REQ_VALUE = 53;
    /**
     * <code>MSG_EMS_CANCEL_ORDER_RSP = 54;</code>
     */
    public static final int MSG_EMS_CANCEL_ORDER_RSP_VALUE = 54;
    /**
     * <code>MSG_MISC_GET_TDTICKET_REQ = 60;</code>
     *
     * <pre>
     * MISC Interface
     * </pre>
     */
    public static final int MSG_MISC_GET_TDTICKET_REQ_VALUE = 60;
    /**
     * <code>MSG_MISC_GET_TDTICKET_RSP = 61;</code>
     */
    public static final int MSG_MISC_GET_TDTICKET_RSP_VALUE = 61;
    /**
     * <code>MSG_MISC_SELF_MESSAGE = 62;</code>
     */
    public static final int MSG_MISC_SELF_MESSAGE_VALUE = 62;
    /**
     * <code>MSG_TRANS_TRANSACTION = 91;</code>
     *
     * <pre>
     * Transaction interface
     * </pre>
     */
    public static final int MSG_TRANS_TRANSACTION_VALUE = 91;
    /**
     * <code>MSG_TRANS_GET_TRANSACTION_REQ = 92;</code>
     */
    public static final int MSG_TRANS_GET_TRANSACTION_REQ_VALUE = 92;
    /**
     * <code>MSG_TRANS_GET_TRANSACTION_RSP = 93;</code>
     */
    public static final int MSG_TRANS_GET_TRANSACTION_RSP_VALUE = 93;
    /**
     * <code>MSG_ORDER_ORDER = 94;</code>
     *
     * <pre>
     *Order interface
     * </pre>
     */
    public static final int MSG_ORDER_ORDER_VALUE = 94;
    /**
     * <code>MSG_ORDER_GET_ORDER_REQ = 95;</code>
     */
    public static final int MSG_ORDER_GET_ORDER_REQ_VALUE = 95;
    /**
     * <code>MSG_ORDER_GET_ORDER_RSP = 96;</code>
     */
    public static final int MSG_ORDER_GET_ORDER_RSP_VALUE = 96;


    public final int getNumber() { return value; }

    public static MsgType valueOf(int value) {
      switch (value) {
        case 0: return MSG_SYS_INIT;
        case 1: return MSG_SYS_TIMER;
        case 2: return MSG_LOW_HEARTBEAT_REQ;
        case 3: return MSG_LOW_HEARTBEAT_RSP;
        case 10: return MSG_TD_ORDER_REQ;
        case 11: return MSG_TD_ORDER_RSP;
        case 12: return MSG_TD_ORDER_REPORT_IND;
        case 13: return MSG_TD_QUERY_ACCOUNT_REQ;
        case 14: return MSG_TD_QUERY_ACCOUNT_RSP;
        case 15: return MSG_TD_QUERY_POSITION_REQ;
        case 16: return MSG_TD_QUERY_POSITION_RSP;
        case 17: return MSG_TD_CANCEL_ORDER_REQ;
        case 18: return MSG_TD_CANCEL_ORDER_RSP;
        case 80: return MSG_TD_QUERY_TRADE_REQ;
        case 81: return MSG_TD_QUERY_TRADE_RSP;
        case 20: return MSG_QMS_MARKETQUOTE_REQ;
        case 21: return MSG_QMS_MARKETQUOTE_RSP;
        case 22: return MSG_QMS_BAR_1M_REQ;
        case 23: return MSG_QMS_BAR_1M_RSP;
        case 24: return MSG_QMS_STRATEGY_MARKETQUOTES_REQ;
        case 25: return MSG_QMS_STRATEGY_MARKETQUOTES_RSP;
        case 26: return MSG_QMS_STRATEGY_SUBSCRIBE_REQ;
        case 27: return MSG_QMS_STRATEGY_SUBSCRIBE_RSP;
        case 31: return MSG_MD_MARKETDATA_IND;
        case 40: return MSG_OMS_GOAL_PORTFOLIO_REQ;
        case 41: return MSG_OMS_GOAL_PORTFOLIO_RSP;
        case 42: return MSG_OMS_QUERY_PORTFOLIO_REQ;
        case 43: return MSG_OMS_QUERY_PORTFOLIO_RSP;
        case 44: return MSG_OMS_SET_PANIC_REQ;
        case 45: return MSG_OMS_SET_PANIC_RSP;
        case 46: return MSG_OMS_SYNC_ACCOUNT_REQ;
        case 47: return MSG_OMS_SYNC_ACCOUNT_RSP;
        case 48: return MSG_OMS_QUERY_ACCOUNT_REQ;
        case 49: return MSG_OMS_QUERY_ACCOUNT_RSP;
        case 70: return MSG_OMS_BASKET_ORDER_REQ;
        case 71: return MSG_OMS_BASKET_ORDER_RSP;
        case 72: return MSG_OMS_STOP_PORTFOLIO_REQ;
        case 73: return MSG_OMS_STOP_PORTFOLIO_RSP;
        case 50: return MSG_EMS_ORDER_REQ;
        case 51: return MSG_EMS_ORDER_RSP;
        case 52: return MSG_EMS_ORDER_REPORT_IND;
        case 53: return MSG_EMS_CANCEL_ORDER_REQ;
        case 54: return MSG_EMS_CANCEL_ORDER_RSP;
        case 60: return MSG_MISC_GET_TDTICKET_REQ;
        case 61: return MSG_MISC_GET_TDTICKET_RSP;
        case 62: return MSG_MISC_SELF_MESSAGE;
        case 91: return MSG_TRANS_TRANSACTION;
        case 92: return MSG_TRANS_GET_TRANSACTION_REQ;
        case 93: return MSG_TRANS_GET_TRANSACTION_RSP;
        case 94: return MSG_ORDER_ORDER;
        case 95: return MSG_ORDER_GET_ORDER_REQ;
        case 96: return MSG_ORDER_GET_ORDER_RSP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jzs.msg.Jzs.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MsgType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jzs.msg.MsgType)
  }

  public interface MsgHeadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required fixed32 tid = 1;
    /**
     * <code>required fixed32 tid = 1;</code>
     */
    boolean hasTid();
    /**
     * <code>required fixed32 tid = 1;</code>
     */
    int getTid();

    // required string src = 2;
    /**
     * <code>required string src = 2;</code>
     */
    boolean hasSrc();
    /**
     * <code>required string src = 2;</code>
     */
    java.lang.String getSrc();
    /**
     * <code>required string src = 2;</code>
     */
    com.google.protobuf.ByteString
        getSrcBytes();

    // required string dst = 3;
    /**
     * <code>required string dst = 3;</code>
     */
    boolean hasDst();
    /**
     * <code>required string dst = 3;</code>
     */
    java.lang.String getDst();
    /**
     * <code>required string dst = 3;</code>
     */
    com.google.protobuf.ByteString
        getDstBytes();

    // optional bool compressed = 4;
    /**
     * <code>optional bool compressed = 4;</code>
     */
    boolean hasCompressed();
    /**
     * <code>optional bool compressed = 4;</code>
     */
    boolean getCompressed();
  }
  /**
   * Protobuf type {@code jzs.msg.MsgHead}
   */
  public static final class MsgHead extends
      com.google.protobuf.GeneratedMessage
      implements MsgHeadOrBuilder {
    // Use MsgHead.newBuilder() to construct.
    private MsgHead(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgHead(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgHead defaultInstance;
    public static MsgHead getDefaultInstance() {
      return defaultInstance;
    }

    public MsgHead getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              tid_ = input.readFixed32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              src_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              dst_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              compressed_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jzs.msg.Jzs.internal_static_jzs_msg_MsgHead_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jzs.msg.Jzs.internal_static_jzs_msg_MsgHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jzs.msg.Jzs.MsgHead.class, jzs.msg.Jzs.MsgHead.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgHead> PARSER =
        new com.google.protobuf.AbstractParser<MsgHead>() {
      public MsgHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgHead(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgHead> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required fixed32 tid = 1;
    public static final int TID_FIELD_NUMBER = 1;
    private int tid_;
    /**
     * <code>required fixed32 tid = 1;</code>
     */
    public boolean hasTid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed32 tid = 1;</code>
     */
    public int getTid() {
      return tid_;
    }

    // required string src = 2;
    public static final int SRC_FIELD_NUMBER = 2;
    private java.lang.Object src_;
    /**
     * <code>required string src = 2;</code>
     */
    public boolean hasSrc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string src = 2;</code>
     */
    public java.lang.String getSrc() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          src_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string src = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSrcBytes() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        src_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string dst = 3;
    public static final int DST_FIELD_NUMBER = 3;
    private java.lang.Object dst_;
    /**
     * <code>required string dst = 3;</code>
     */
    public boolean hasDst() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string dst = 3;</code>
     */
    public java.lang.String getDst() {
      java.lang.Object ref = dst_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dst_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dst = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDstBytes() {
      java.lang.Object ref = dst_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool compressed = 4;
    public static final int COMPRESSED_FIELD_NUMBER = 4;
    private boolean compressed_;
    /**
     * <code>optional bool compressed = 4;</code>
     */
    public boolean hasCompressed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool compressed = 4;</code>
     */
    public boolean getCompressed() {
      return compressed_;
    }

    private void initFields() {
      tid_ = 0;
      src_ = "";
      dst_ = "";
      compressed_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSrc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDst()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed32(1, tid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSrcBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDstBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, compressed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, tid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSrcBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDstBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, compressed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jzs.msg.Jzs.MsgHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.Jzs.MsgHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.Jzs.MsgHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.Jzs.MsgHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.Jzs.MsgHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.Jzs.MsgHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jzs.msg.Jzs.MsgHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jzs.msg.Jzs.MsgHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jzs.msg.Jzs.MsgHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.Jzs.MsgHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jzs.msg.Jzs.MsgHead prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jzs.msg.MsgHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jzs.msg.Jzs.MsgHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jzs.msg.Jzs.internal_static_jzs_msg_MsgHead_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jzs.msg.Jzs.internal_static_jzs_msg_MsgHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jzs.msg.Jzs.MsgHead.class, jzs.msg.Jzs.MsgHead.Builder.class);
      }

      // Construct using jzs.msg.Jzs.MsgHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        src_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dst_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        compressed_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jzs.msg.Jzs.internal_static_jzs_msg_MsgHead_descriptor;
      }

      public jzs.msg.Jzs.MsgHead getDefaultInstanceForType() {
        return jzs.msg.Jzs.MsgHead.getDefaultInstance();
      }

      public jzs.msg.Jzs.MsgHead build() {
        jzs.msg.Jzs.MsgHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jzs.msg.Jzs.MsgHead buildPartial() {
        jzs.msg.Jzs.MsgHead result = new jzs.msg.Jzs.MsgHead(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tid_ = tid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.src_ = src_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dst_ = dst_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.compressed_ = compressed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jzs.msg.Jzs.MsgHead) {
          return mergeFrom((jzs.msg.Jzs.MsgHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jzs.msg.Jzs.MsgHead other) {
        if (other == jzs.msg.Jzs.MsgHead.getDefaultInstance()) return this;
        if (other.hasTid()) {
          setTid(other.getTid());
        }
        if (other.hasSrc()) {
          bitField0_ |= 0x00000002;
          src_ = other.src_;
          onChanged();
        }
        if (other.hasDst()) {
          bitField0_ |= 0x00000004;
          dst_ = other.dst_;
          onChanged();
        }
        if (other.hasCompressed()) {
          setCompressed(other.getCompressed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTid()) {
          
          return false;
        }
        if (!hasSrc()) {
          
          return false;
        }
        if (!hasDst()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jzs.msg.Jzs.MsgHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jzs.msg.Jzs.MsgHead) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required fixed32 tid = 1;
      private int tid_ ;
      /**
       * <code>required fixed32 tid = 1;</code>
       */
      public boolean hasTid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed32 tid = 1;</code>
       */
      public int getTid() {
        return tid_;
      }
      /**
       * <code>required fixed32 tid = 1;</code>
       */
      public Builder setTid(int value) {
        bitField0_ |= 0x00000001;
        tid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 tid = 1;</code>
       */
      public Builder clearTid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tid_ = 0;
        onChanged();
        return this;
      }

      // required string src = 2;
      private java.lang.Object src_ = "";
      /**
       * <code>required string src = 2;</code>
       */
      public boolean hasSrc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string src = 2;</code>
       */
      public java.lang.String getSrc() {
        java.lang.Object ref = src_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          src_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string src = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSrcBytes() {
        java.lang.Object ref = src_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          src_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string src = 2;</code>
       */
      public Builder setSrc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        src_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string src = 2;</code>
       */
      public Builder clearSrc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        src_ = getDefaultInstance().getSrc();
        onChanged();
        return this;
      }
      /**
       * <code>required string src = 2;</code>
       */
      public Builder setSrcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        src_ = value;
        onChanged();
        return this;
      }

      // required string dst = 3;
      private java.lang.Object dst_ = "";
      /**
       * <code>required string dst = 3;</code>
       */
      public boolean hasDst() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string dst = 3;</code>
       */
      public java.lang.String getDst() {
        java.lang.Object ref = dst_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dst_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dst = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDstBytes() {
        java.lang.Object ref = dst_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dst_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dst = 3;</code>
       */
      public Builder setDst(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dst = 3;</code>
       */
      public Builder clearDst() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dst_ = getDefaultInstance().getDst();
        onChanged();
        return this;
      }
      /**
       * <code>required string dst = 3;</code>
       */
      public Builder setDstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dst_ = value;
        onChanged();
        return this;
      }

      // optional bool compressed = 4;
      private boolean compressed_ ;
      /**
       * <code>optional bool compressed = 4;</code>
       */
      public boolean hasCompressed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool compressed = 4;</code>
       */
      public boolean getCompressed() {
        return compressed_;
      }
      /**
       * <code>optional bool compressed = 4;</code>
       */
      public Builder setCompressed(boolean value) {
        bitField0_ |= 0x00000008;
        compressed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool compressed = 4;</code>
       */
      public Builder clearCompressed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        compressed_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jzs.msg.MsgHead)
    }

    static {
      defaultInstance = new MsgHead(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jzs.msg.MsgHead)
  }

  public interface MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .jzs.msg.MsgHead head = 1;
    /**
     * <code>required .jzs.msg.MsgHead head = 1;</code>
     */
    boolean hasHead();
    /**
     * <code>required .jzs.msg.MsgHead head = 1;</code>
     */
    jzs.msg.Jzs.MsgHead getHead();
    /**
     * <code>required .jzs.msg.MsgHead head = 1;</code>
     */
    jzs.msg.Jzs.MsgHeadOrBuilder getHeadOrBuilder();

    // required bytes body = 2;
    /**
     * <code>required bytes body = 2;</code>
     */
    boolean hasBody();
    /**
     * <code>required bytes body = 2;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code jzs.msg.Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }

    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              jzs.msg.Jzs.MsgHead.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = head_.toBuilder();
              }
              head_ = input.readMessage(jzs.msg.Jzs.MsgHead.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(head_);
                head_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jzs.msg.Jzs.internal_static_jzs_msg_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jzs.msg.Jzs.internal_static_jzs_msg_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jzs.msg.Jzs.Msg.class, jzs.msg.Jzs.Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg> PARSER =
        new com.google.protobuf.AbstractParser<Msg>() {
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .jzs.msg.MsgHead head = 1;
    public static final int HEAD_FIELD_NUMBER = 1;
    private jzs.msg.Jzs.MsgHead head_;
    /**
     * <code>required .jzs.msg.MsgHead head = 1;</code>
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .jzs.msg.MsgHead head = 1;</code>
     */
    public jzs.msg.Jzs.MsgHead getHead() {
      return head_;
    }
    /**
     * <code>required .jzs.msg.MsgHead head = 1;</code>
     */
    public jzs.msg.Jzs.MsgHeadOrBuilder getHeadOrBuilder() {
      return head_;
    }

    // required bytes body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>required bytes body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes body = 2;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private void initFields() {
      head_ = jzs.msg.Jzs.MsgHead.getDefaultInstance();
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHead().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, body_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jzs.msg.Jzs.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.Jzs.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.Jzs.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.Jzs.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.Jzs.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.Jzs.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jzs.msg.Jzs.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jzs.msg.Jzs.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jzs.msg.Jzs.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.Jzs.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jzs.msg.Jzs.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jzs.msg.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jzs.msg.Jzs.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jzs.msg.Jzs.internal_static_jzs_msg_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jzs.msg.Jzs.internal_static_jzs_msg_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jzs.msg.Jzs.Msg.class, jzs.msg.Jzs.Msg.Builder.class);
      }

      // Construct using jzs.msg.Jzs.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeadFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headBuilder_ == null) {
          head_ = jzs.msg.Jzs.MsgHead.getDefaultInstance();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jzs.msg.Jzs.internal_static_jzs_msg_Msg_descriptor;
      }

      public jzs.msg.Jzs.Msg getDefaultInstanceForType() {
        return jzs.msg.Jzs.Msg.getDefaultInstance();
      }

      public jzs.msg.Jzs.Msg build() {
        jzs.msg.Jzs.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jzs.msg.Jzs.Msg buildPartial() {
        jzs.msg.Jzs.Msg result = new jzs.msg.Jzs.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jzs.msg.Jzs.Msg) {
          return mergeFrom((jzs.msg.Jzs.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jzs.msg.Jzs.Msg other) {
        if (other == jzs.msg.Jzs.Msg.getDefaultInstance()) return this;
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHead()) {
          
          return false;
        }
        if (!hasBody()) {
          
          return false;
        }
        if (!getHead().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jzs.msg.Jzs.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jzs.msg.Jzs.Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .jzs.msg.MsgHead head = 1;
      private jzs.msg.Jzs.MsgHead head_ = jzs.msg.Jzs.MsgHead.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          jzs.msg.Jzs.MsgHead, jzs.msg.Jzs.MsgHead.Builder, jzs.msg.Jzs.MsgHeadOrBuilder> headBuilder_;
      /**
       * <code>required .jzs.msg.MsgHead head = 1;</code>
       */
      public boolean hasHead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .jzs.msg.MsgHead head = 1;</code>
       */
      public jzs.msg.Jzs.MsgHead getHead() {
        if (headBuilder_ == null) {
          return head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      /**
       * <code>required .jzs.msg.MsgHead head = 1;</code>
       */
      public Builder setHead(jzs.msg.Jzs.MsgHead value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .jzs.msg.MsgHead head = 1;</code>
       */
      public Builder setHead(
          jzs.msg.Jzs.MsgHead.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .jzs.msg.MsgHead head = 1;</code>
       */
      public Builder mergeHead(jzs.msg.Jzs.MsgHead value) {
        if (headBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              head_ != jzs.msg.Jzs.MsgHead.getDefaultInstance()) {
            head_ =
              jzs.msg.Jzs.MsgHead.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .jzs.msg.MsgHead head = 1;</code>
       */
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = jzs.msg.Jzs.MsgHead.getDefaultInstance();
          onChanged();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .jzs.msg.MsgHead head = 1;</code>
       */
      public jzs.msg.Jzs.MsgHead.Builder getHeadBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      /**
       * <code>required .jzs.msg.MsgHead head = 1;</code>
       */
      public jzs.msg.Jzs.MsgHeadOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_;
        }
      }
      /**
       * <code>required .jzs.msg.MsgHead head = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          jzs.msg.Jzs.MsgHead, jzs.msg.Jzs.MsgHead.Builder, jzs.msg.Jzs.MsgHeadOrBuilder> 
          getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              jzs.msg.Jzs.MsgHead, jzs.msg.Jzs.MsgHead.Builder, jzs.msg.Jzs.MsgHeadOrBuilder>(
                  head_,
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }

      // required bytes body = 2;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>required bytes body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jzs.msg.Msg)
    }

    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jzs.msg.Msg)
  }

  public interface SysTimerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 id = 1;
    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    // required uint32 interval = 2;
    /**
     * <code>required uint32 interval = 2;</code>
     */
    boolean hasInterval();
    /**
     * <code>required uint32 interval = 2;</code>
     */
    int getInterval();

    // required int64 data = 3;
    /**
     * <code>required int64 data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>required int64 data = 3;</code>
     */
    long getData();
  }
  /**
   * Protobuf type {@code jzs.msg.SysTimer}
   */
  public static final class SysTimer extends
      com.google.protobuf.GeneratedMessage
      implements SysTimerOrBuilder {
    // Use SysTimer.newBuilder() to construct.
    private SysTimer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SysTimer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SysTimer defaultInstance;
    public static SysTimer getDefaultInstance() {
      return defaultInstance;
    }

    public SysTimer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SysTimer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              interval_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              data_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jzs.msg.Jzs.internal_static_jzs_msg_SysTimer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jzs.msg.Jzs.internal_static_jzs_msg_SysTimer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jzs.msg.Jzs.SysTimer.class, jzs.msg.Jzs.SysTimer.Builder.class);
    }

    public static com.google.protobuf.Parser<SysTimer> PARSER =
        new com.google.protobuf.AbstractParser<SysTimer>() {
      public SysTimer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SysTimer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SysTimer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required uint32 interval = 2;
    public static final int INTERVAL_FIELD_NUMBER = 2;
    private int interval_;
    /**
     * <code>required uint32 interval = 2;</code>
     */
    public boolean hasInterval() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 interval = 2;</code>
     */
    public int getInterval() {
      return interval_;
    }

    // required int64 data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private long data_;
    /**
     * <code>required int64 data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 data = 3;</code>
     */
    public long getData() {
      return data_;
    }

    private void initFields() {
      id_ = 0;
      interval_ = 0;
      data_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInterval()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, interval_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, interval_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jzs.msg.Jzs.SysTimer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.Jzs.SysTimer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.Jzs.SysTimer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.Jzs.SysTimer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.Jzs.SysTimer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.Jzs.SysTimer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jzs.msg.Jzs.SysTimer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jzs.msg.Jzs.SysTimer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jzs.msg.Jzs.SysTimer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.Jzs.SysTimer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jzs.msg.Jzs.SysTimer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jzs.msg.SysTimer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jzs.msg.Jzs.SysTimerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jzs.msg.Jzs.internal_static_jzs_msg_SysTimer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jzs.msg.Jzs.internal_static_jzs_msg_SysTimer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jzs.msg.Jzs.SysTimer.class, jzs.msg.Jzs.SysTimer.Builder.class);
      }

      // Construct using jzs.msg.Jzs.SysTimer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        interval_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jzs.msg.Jzs.internal_static_jzs_msg_SysTimer_descriptor;
      }

      public jzs.msg.Jzs.SysTimer getDefaultInstanceForType() {
        return jzs.msg.Jzs.SysTimer.getDefaultInstance();
      }

      public jzs.msg.Jzs.SysTimer build() {
        jzs.msg.Jzs.SysTimer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jzs.msg.Jzs.SysTimer buildPartial() {
        jzs.msg.Jzs.SysTimer result = new jzs.msg.Jzs.SysTimer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.interval_ = interval_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jzs.msg.Jzs.SysTimer) {
          return mergeFrom((jzs.msg.Jzs.SysTimer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jzs.msg.Jzs.SysTimer other) {
        if (other == jzs.msg.Jzs.SysTimer.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasInterval()) {
          setInterval(other.getInterval());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasInterval()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jzs.msg.Jzs.SysTimer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jzs.msg.Jzs.SysTimer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 id = 1;
      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required uint32 interval = 2;
      private int interval_ ;
      /**
       * <code>required uint32 interval = 2;</code>
       */
      public boolean hasInterval() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 interval = 2;</code>
       */
      public int getInterval() {
        return interval_;
      }
      /**
       * <code>required uint32 interval = 2;</code>
       */
      public Builder setInterval(int value) {
        bitField0_ |= 0x00000002;
        interval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 interval = 2;</code>
       */
      public Builder clearInterval() {
        bitField0_ = (bitField0_ & ~0x00000002);
        interval_ = 0;
        onChanged();
        return this;
      }

      // required int64 data = 3;
      private long data_ ;
      /**
       * <code>required int64 data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 data = 3;</code>
       */
      public long getData() {
        return data_;
      }
      /**
       * <code>required int64 data = 3;</code>
       */
      public Builder setData(long value) {
        bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jzs.msg.SysTimer)
    }

    static {
      defaultInstance = new SysTimer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jzs.msg.SysTimer)
  }

  public interface SysInitOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code jzs.msg.SysInit}
   */
  public static final class SysInit extends
      com.google.protobuf.GeneratedMessage
      implements SysInitOrBuilder {
    // Use SysInit.newBuilder() to construct.
    private SysInit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SysInit(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SysInit defaultInstance;
    public static SysInit getDefaultInstance() {
      return defaultInstance;
    }

    public SysInit getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SysInit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jzs.msg.Jzs.internal_static_jzs_msg_SysInit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jzs.msg.Jzs.internal_static_jzs_msg_SysInit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jzs.msg.Jzs.SysInit.class, jzs.msg.Jzs.SysInit.Builder.class);
    }

    public static com.google.protobuf.Parser<SysInit> PARSER =
        new com.google.protobuf.AbstractParser<SysInit>() {
      public SysInit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SysInit(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SysInit> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jzs.msg.Jzs.SysInit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.Jzs.SysInit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.Jzs.SysInit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jzs.msg.Jzs.SysInit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jzs.msg.Jzs.SysInit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.Jzs.SysInit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jzs.msg.Jzs.SysInit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jzs.msg.Jzs.SysInit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jzs.msg.Jzs.SysInit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jzs.msg.Jzs.SysInit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jzs.msg.Jzs.SysInit prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jzs.msg.SysInit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jzs.msg.Jzs.SysInitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jzs.msg.Jzs.internal_static_jzs_msg_SysInit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jzs.msg.Jzs.internal_static_jzs_msg_SysInit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jzs.msg.Jzs.SysInit.class, jzs.msg.Jzs.SysInit.Builder.class);
      }

      // Construct using jzs.msg.Jzs.SysInit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jzs.msg.Jzs.internal_static_jzs_msg_SysInit_descriptor;
      }

      public jzs.msg.Jzs.SysInit getDefaultInstanceForType() {
        return jzs.msg.Jzs.SysInit.getDefaultInstance();
      }

      public jzs.msg.Jzs.SysInit build() {
        jzs.msg.Jzs.SysInit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jzs.msg.Jzs.SysInit buildPartial() {
        jzs.msg.Jzs.SysInit result = new jzs.msg.Jzs.SysInit(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jzs.msg.Jzs.SysInit) {
          return mergeFrom((jzs.msg.Jzs.SysInit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jzs.msg.Jzs.SysInit other) {
        if (other == jzs.msg.Jzs.SysInit.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jzs.msg.Jzs.SysInit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jzs.msg.Jzs.SysInit) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jzs.msg.SysInit)
    }

    static {
      defaultInstance = new SysInit(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jzs.msg.SysInit)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jzs_msg_MsgHead_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jzs_msg_MsgHead_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jzs_msg_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jzs_msg_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jzs_msg_SysTimer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jzs_msg_SysTimer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jzs_msg_SysInit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jzs_msg_SysInit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tjzs.proto\022\007jzs.msg\"D\n\007MsgHead\022\013\n\003tid\030\001" +
      " \002(\007\022\013\n\003src\030\002 \002(\t\022\013\n\003dst\030\003 \002(\t\022\022\n\ncompre" +
      "ssed\030\004 \001(\010\"3\n\003Msg\022\036\n\004head\030\001 \002(\0132\020.jzs.ms" +
      "g.MsgHead\022\014\n\004body\030\002 \002(\014\"6\n\010SysTimer\022\n\n\002i" +
      "d\030\001 \002(\r\022\020\n\010interval\030\002 \002(\r\022\014\n\004data\030\003 \002(\003\"" +
      "\t\n\007SysInit*\363\013\n\007MsgType\022\020\n\014MSG_SYS_INIT\020\000" +
      "\022\021\n\rMSG_SYS_TIMER\020\001\022\031\n\025MSG_LOW_HEARTBEAT" +
      "_REQ\020\002\022\031\n\025MSG_LOW_HEARTBEAT_RSP\020\003\022\024\n\020MSG" +
      "_TD_ORDER_REQ\020\n\022\024\n\020MSG_TD_ORDER_RSP\020\013\022\033\n" +
      "\027MSG_TD_ORDER_REPORT_IND\020\014\022\034\n\030MSG_TD_QUE",
      "RY_ACCOUNT_REQ\020\r\022\034\n\030MSG_TD_QUERY_ACCOUNT" +
      "_RSP\020\016\022\035\n\031MSG_TD_QUERY_POSITION_REQ\020\017\022\035\n" +
      "\031MSG_TD_QUERY_POSITION_RSP\020\020\022\033\n\027MSG_TD_C" +
      "ANCEL_ORDER_REQ\020\021\022\033\n\027MSG_TD_CANCEL_ORDER" +
      "_RSP\020\022\022\032\n\026MSG_TD_QUERY_TRADE_REQ\020P\022\032\n\026MS" +
      "G_TD_QUERY_TRADE_RSP\020Q\022\033\n\027MSG_QMS_MARKET" +
      "QUOTE_REQ\020\024\022\033\n\027MSG_QMS_MARKETQUOTE_RSP\020\025" +
      "\022\026\n\022MSG_QMS_BAR_1M_REQ\020\026\022\026\n\022MSG_QMS_BAR_" +
      "1M_RSP\020\027\022%\n!MSG_QMS_STRATEGY_MARKETQUOTE" +
      "S_REQ\020\030\022%\n!MSG_QMS_STRATEGY_MARKETQUOTES",
      "_RSP\020\031\022\"\n\036MSG_QMS_STRATEGY_SUBSCRIBE_REQ" +
      "\020\032\022\"\n\036MSG_QMS_STRATEGY_SUBSCRIBE_RSP\020\033\022\031" +
      "\n\025MSG_MD_MARKETDATA_IND\020\037\022\036\n\032MSG_OMS_GOA" +
      "L_PORTFOLIO_REQ\020(\022\036\n\032MSG_OMS_GOAL_PORTFO" +
      "LIO_RSP\020)\022\037\n\033MSG_OMS_QUERY_PORTFOLIO_REQ" +
      "\020*\022\037\n\033MSG_OMS_QUERY_PORTFOLIO_RSP\020+\022\031\n\025M" +
      "SG_OMS_SET_PANIC_REQ\020,\022\031\n\025MSG_OMS_SET_PA" +
      "NIC_RSP\020-\022\034\n\030MSG_OMS_SYNC_ACCOUNT_REQ\020.\022" +
      "\034\n\030MSG_OMS_SYNC_ACCOUNT_RSP\020/\022\035\n\031MSG_OMS" +
      "_QUERY_ACCOUNT_REQ\0200\022\035\n\031MSG_OMS_QUERY_AC",
      "COUNT_RSP\0201\022\034\n\030MSG_OMS_BASKET_ORDER_REQ\020" +
      "F\022\034\n\030MSG_OMS_BASKET_ORDER_RSP\020G\022\036\n\032MSG_O" +
      "MS_STOP_PORTFOLIO_REQ\020H\022\036\n\032MSG_OMS_STOP_" +
      "PORTFOLIO_RSP\020I\022\025\n\021MSG_EMS_ORDER_REQ\0202\022\025" +
      "\n\021MSG_EMS_ORDER_RSP\0203\022\034\n\030MSG_EMS_ORDER_R" +
      "EPORT_IND\0204\022\034\n\030MSG_EMS_CANCEL_ORDER_REQ\020" +
      "5\022\034\n\030MSG_EMS_CANCEL_ORDER_RSP\0206\022\035\n\031MSG_M" +
      "ISC_GET_TDTICKET_REQ\020<\022\035\n\031MSG_MISC_GET_T" +
      "DTICKET_RSP\020=\022\031\n\025MSG_MISC_SELF_MESSAGE\020>" +
      "\022\031\n\025MSG_TRANS_TRANSACTION\020[\022!\n\035MSG_TRANS",
      "_GET_TRANSACTION_REQ\020\\\022!\n\035MSG_TRANS_GET_" +
      "TRANSACTION_RSP\020]\022\023\n\017MSG_ORDER_ORDER\020^\022\033" +
      "\n\027MSG_ORDER_GET_ORDER_REQ\020_\022\033\n\027MSG_ORDER" +
      "_GET_ORDER_RSP\020`"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_jzs_msg_MsgHead_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_jzs_msg_MsgHead_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jzs_msg_MsgHead_descriptor,
              new java.lang.String[] { "Tid", "Src", "Dst", "Compressed", });
          internal_static_jzs_msg_Msg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_jzs_msg_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jzs_msg_Msg_descriptor,
              new java.lang.String[] { "Head", "Body", });
          internal_static_jzs_msg_SysTimer_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_jzs_msg_SysTimer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jzs_msg_SysTimer_descriptor,
              new java.lang.String[] { "Id", "Interval", "Data", });
          internal_static_jzs_msg_SysInit_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_jzs_msg_SysInit_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jzs_msg_SysInit_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
